config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "dashboard#show"
  get "/friends", to: "friends#show"
  get "/tweets", to: "users#show", as: :tweets
  get "/friend_tweets", to: "users#show_friend_tweets", as: :friend_tweets
  # get "/byhandle_tweets", to: "byhandle#show_handle_tweets", as: :byhandle_tweets
  # get "/turing_tweets", to: "turing#show", 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.token              = auth_info.credentials.token
      new_user.secret             = auth_info.credentials.secret
      new_user.provider           = auth_info.provider
      new_user.profile_image      = auth_info.info.image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def show
    @friends = twitter.get_friends
  end

  private

    def twitter
      @twitter ||= TwitterService.new(current_user)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
   if user = User.from_omniauth(request.env["omniauth.auth"])
     session[:user_id] = user.id
   end
   redirect_to dashboard_path(current_user.screen_name)
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @tweets  = twitter.get_tweets(current_user.screen_name)
  end

  def show_friend_tweets
    @tweets = twitter.get_tweets(params[:user][0])
    @friend = params[:user]
  end

  private

    def twitter
      @twitter ||= TwitterService.new(current_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div class="container text-center transparent2">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="landing_text">Analyze Sentiments Dashboard</h1>
      <p><%= link_to "Analyze Your Tweets", tweets_path, class:"btn btn-lg btn-primary btn-nav" %></p>
      <p><%= link_to "Analyze Your Friends Tweets", friends_path, class:"btn btn-lg btn-primary btn-nav" %></p>
      <!-- <p>link_to "Analyze Any Turing Tweets", turing_path, class:"btn btn-primary btn-nav"</p> -->

      <!-- <p>link_to "Analyze Any Twitter Handle's Tweets", handle_path, class:"btn btn-primary btn-nav"</p> -->
    </ul>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<div class="container text-center transparent2">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="landing_text">Select a friend and analyze their tweets</h1>
    </div>
  </div>

  <div class="row">
    <% @friends.each do |friend| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="<%= friend[1] %>" alt="...">
          <div class="caption">
            <h3><%= friend[0] %></h3>
            <p>...</p>
            <p><a href="<%= friend_tweets_path(user: friend) %>" class="btn btn-primary" role="button">Analyze Tweets</a></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <h1 class="display-3">Positive or Negative?</h1>
  <!-- <h1 class="display-3">Analyze your tweets!</h1> -->

  <p class="lead">Analyze tweets to discover their sentiment.</p>
  <hr class="m-y-2">
  <p class="lead">
    <% if current_user %>
        <%= link_to "Back to my Dashboard!", dashboard_path, class:"btn btn-primary btn-lg" %>
      <% else %>
        <%= link_to "Sign in with Twitter", twitter_login_path, class:"btn btn-primary btn-lg" %>
    <% end %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetishSentiments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <%= render partial: "shared/nav" %>

    <div class="container">
 <div class="row">
 <div class="col-md-12">
 <%= yield %>
 </div>
 </div>
</div>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="container">
  <nav class="navbar" role="navigation">
    <div class="navbar-header">
      <!-- link_to image_tag("tweetish_sentiments_logo.jpg"), root_path -->
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if !current_user %>
      <% else %>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Back to Dashboard", dashboard_path, class:"btn btn-primary" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#" class="btn btn-primary btn-nav">Analyze Tweets</a></li> -->
        <!-- <li>link_to "Friends", friends_path, class:"btn btn-primary btn-nav"</li> -->
        <li><%= link_to "Log Out", logout_path, class:"btn btn-primary" %></li>
      </ul>
    <% end %>
    </div><!-- /.navbar-collapse -->
</nav>
</div>

app/views/shared/_tweet_analysis_table.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="tweets">
      <table class="table">
        <tr>          <div class= "text-center"><%= image_tag("positive_emoji.jpg", :alt => "Trending Positive", style:"height: 50px;") %><%= image_tag("negative_emoji.jpg", :alt => "Trending Negative", style:"height: 50px;") %></div>

        </tr>
        <tr class="landing_text">
          <th><h1>Tweets</h1></th>
          <th><h1>Sentiment</h1>
        </th>
          <!-- <th><h2>Score</h2></th> -->
        </tr>
        <% @tweets.each do |tweet| %>
          <tr class="bg-primary"">
            <td><%= tweet[0] %></td>
            <td><%= tweet[1][0] %></td>
            <!-- <td> tweet[1][1].to_s + '%''</td> -->
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="landing_text">Analyze your last 10 tweets</h1>
      <!-- <p><%#= link_to "Analyze Your Friends Tweets", twitter_login_path, class:"btn btn-primary btn-nav" %></p> -->
    </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= image_tag current_user.profile_image %><br>
      <%= current_user.screen_name %>
    </ul>
    </div>
  </div>

    <%= render partial: "shared/tweet_analysis_table" %>
</div>

app/views/users/show_friend_tweets.html.erb
<div class="container text-center transparent2">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="landing_text">Analysis Of <%= @friend[0] %>'s last 10 tweets</h1>
    </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= image_tag @friend[1] %><br>
      <%= @friend[0] %>
    </ul>
    </div>
  </div>

    <%= render partial: "shared/tweet_analysis_table" %>

</div>